name: Cameron Osborn Consulting
favicon: null
layout_spectrum: 0.00511
typography_spectrum: 0.84506
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414042'
    - '#36b3a8'
    - '#ffffff'
    - '#778b89'
    - '#abb7b6'
  brandStrength: 0.9710332537069917
  lightness: 0.6087707942351699
  saturation: 0.4375
  rhythmicContrast: 0.4249625422526151
purpose: []
